baseurl: /
collections:
  tooltips: {output: false}
company_name: ohmeow
default_badges: {colab: true}
defaults:
- scope: {path: '', type: pages}
  values: {comments: true, layout: page, search: true, sidebar: home_sidebar, topnav: topnav}
- scope: {path: '', type: tooltips}
  values: {comments: true, layout: page, search: true, tooltip: true}
description: Taking fastai to the next level
exclude: [.idea/, .gitignore, vendor]
feedback_disable: true
github_editme_path: null
google_analytics: null
google_search: null
highlighter: rouge
kramdown: {auto_ids: true, hard_wrap: false, syntax_highlighter: rouge}
markdown: kramdown
output: web
plugins: [jekyll-remote-theme]
remote_theme: fastai/nbdev-jekyll-theme
repository: ohmeow/blurr
sidebars: [home_sidebar]
site_title: blurr
topnav_title: blurr
twitter_username: waydegilliam
url: https://muellerzr.github.io/blurr
use_math: true
